services:
  haproxy:
    image: haproxy:latest
    container_name: haproxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./code:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb
    restart: always

  php:
    image: php:8.4-fpm
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - ./code:/usr/share/nginx/html
    depends_on:
      - mariadb
      - memcached

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: 123456
      MARIADB_DATABASE: default_database
      MARIADB_USER: user
      MARIADB_PASSWORD: password

  memcached:
    image: memcached:latest
    container_name: memcached
    ports:
      - "11211:11211"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: mariadb
      PMA_USER: user
      PMA_PASSWORD: password
    ports:
      - "5002:80"
    depends_on:
      - mariadb
