services:
  web:
    container_name: my_nginx_web
    image: nginx:latest
    ports:
      - "5001:80"
    volumes:
      - ./code:/usr/share/nginx/html
      - ./site.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db
    restart: always

  php:
    image: php:8.4-fpm
    container_name: my_php
    ports:
      - "9000:9000"
    volumes:
      - ./code:/usr/share/nginx/html

  db:
    image: mysql:8.4
    container_name: my_mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: example_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

